/**
 * @file apps/desktop/src/main/ipc/register-failure-and-defect-ipc.ts
 * Privileged IPC boundary registrations for Failure Intelligence (V6), Jira Integration (V7),
 * and Defect Remediation & QA Reporting (Phases 95-109).
 */

import type { IpcMain, IpcMainInvokeEvent } from 'electron';
import { DESKTOP_CHANNELS, type DesktopErrorCode, type DesktopResult } from '@ai-quality/contracts';

// Failure Intelligence Handlers (Phase 74-87)
import {
  handleCreateFailureCase,
  handleEnsureFailureCase,
  handleGetFailureCase,
  handleListFailureCases,
  handleStartFailureAnalysis,
  handleCompleteFailureAnalysis,
  handleFailFailureAnalysis,
  handleCancelFailureAnalysis,
  handleMarkFailureCaseStale,
  handleListFailureAnalysisRuns,
  handleListFailureEvidenceReferences,
  handleIngestFailureEvidence,
  handleGetFailureEvidencePackage,
  handleVerifyEvidenceIntegrity,
  handleGetEvidenceArtifactContent,
  handleExecuteReproduction,
  handleGetReproductionAttempts,
  handleGetReproducibilitySummary,
  handleCancelReproduction,
  handleClassifyFailure,
  handleGetFailureClassification,
  handleReclassifyFailure,
  handleListFailureClassificationHistory,
  handleEvaluateDecisionIntegrity,
  handleGetDecisionIntegrity,
  handleRecomputeDecisionIntegrity,
  handleListDecisionIntegrityHistory,
  handleAnalyzeFlakiness,
  handleGetFlakinessAnalysis,
  handleReanalyzeFlakiness,
  handleListFlakinessHistory,
  handleSeparateFailureDomain,
  handleGetDomainSeparation,
  handleReevaluateDomainSeparation,
  handleListDomainSeparationHistory,
  handleLocalizeTechnicalCause,
  handleGetTechnicalLocalization,
  handleRelocalizeTechnicalCause,
  handleListLocalizationHistory,
  handleAssessFailureWithAi,
  handleGetFailureAiAssessment,
  handleReassessFailureWithAi,
  handleListFailureAiAssessmentHistory,
  handleAnalyzeRootCause,
  handleGetRootCauseAnalysis,
  handleReanalyzeRootCause,
  handleListRootCauseHistory,
  handleAssessImpact,
  handleGetImpactAssessment,
  handleReassessImpact,
  handleListImpactHistory,
  handleCompareDuplicates,
  handleClusterDefects,
  handleGetCluster,
  handleListClusters,
  handleGetFailureMembership,
  handleMergeClusters,
  handleSplitCluster,
  handleOverrideMembership,
  handleListClusterHistory,
  handleAssessConfidence,
  handleGetConfidence,
  handleReassessConfidence,
  handleListConfidenceHistory,
  handleListEvidenceAttributions,
  handleCreateBugReport,
  handleGetBugReport,
  handleListBugReports,
  handleRegenerateBugReport,
  handleListBugReportHistory,
} from './failure-handlers.js';

// Jira Handlers (Phase 89-94)
import {
  handleCreateJiraConnection,
  handleUpdateJiraConnection,
  handleGetJiraConnection,
  handleDeleteJiraConnection,
  handleValidateJiraConnection,
  handleListJiraAuditLog,
  handleDiscoverJiraSites,
  handleDiscoverJiraProjects,
  handleDiscoverJiraIssueTypes,
  handleDiscoverJiraPriorities,
  handleDiscoverJiraFields,
  handleDiscoverJiraComponents,
  handleDiscoverJiraAssignees,
  handleGetJiraProjectConfig,
  handleSaveJiraProjectConfig,
  handleRefreshJiraProjectConfig,
  handleTestJiraConnectionHealth,
  handleCreateJiraIssue,
  handleGetJiraIssue,
  handleListAttachableEvidence,
  handleAttachEvidence,
  handleGetAttachmentStatus,
  handleEvaluateDuplicate,
  handleLinkExistingIssue,
  handleGetIssueLink,
  handleRegisterProjectEngineer,
  handleListEligibleEngineers,
  handleGetDefectOwnership,
  handleAssignEngineer,
  handleUnassignEngineer,
  handleSyncOwnershipFromJira,
  handleRetryJiraSync,
} from './jira-handlers.js';

// Email Handlers (Phase 95)
import {
  handleGetEmailConfig,
  handleSaveEmailConfig,
  handleTestEmailConnection,
  handleListEmailNotifications,
  handleGetEmailNotification,
  handleRetryEmailNotification,
  handleSendWorkflowNotification,
} from './email-handlers.js';

// Workflow Handlers (Phase 96)
import {
  handleGetWorkflowState,
  handleUpdateInternalStatus,
  handleGetWorkflowStatusMappings,
  handleSaveWorkflowStatusMapping,
  handleDeleteWorkflowStatusMapping,
  handleSyncWorkflowNow,
  handleResolveWorkflowConflict,
  handleListWorkflowSyncEvents,
} from './workflow-handlers.js';

// Reverification Handlers (Phase 97)
import {
  handleGetReverificationState,
  handleEvaluateReverificationEligibility,
  handleCreateReverificationRequest,
  handleGenerateReverificationPlan,
  handleCancelReverification,
  handleListReverificationAuditEvents,
} from './reverification-handlers.js';

// Verification Handlers (Phase 98)
import {
  handleExecuteVerification,
  handleGetVerificationAttempts,
  handleGetVerificationComparison,
  handleCancelVerification,
} from './verification-handlers.js';

// QuickFix Handlers (Phase 99)
import {
  handleEvaluateQuickFixEligibility,
  handleGetQuickFixAssessment,
  handleListQuickFixAssessments,
} from './quick-fix-handlers.js';

// Defect Localization Handlers (Phase 100)
import {
  handleLocalizeDefect,
  handleGetDefectLocalization,
  handleListDefectLocalizations,
  handleInspectCandidateSource,
} from './defect-localization-handlers.js';

// Patch Proposal Handlers (Phase 101)
import {
  handleGeneratePatchProposal,
  handleGetPatchProposal,
  handleListPatchProposals,
  handleWithdrawPatchProposal,
} from './patch-proposal-handlers.js';

// Patch Sandbox Handlers (Phase 102)
import {
  handleCreatePatchSandbox,
  handleApplyPatchToSandbox,
  handleGetPatchSandbox,
  handleListPatchSandboxes,
  handleDestroyPatchSandbox,
} from './patch-sandbox-handlers.js';

// Patch Validation Handlers (Phase 103)
import {
  handleExecutePatchValidation,
  handleGetPatchValidation,
  handleListPatchValidations,
  handleCancelPatchValidation,
} from './patch-validation-handlers.js';

// Patch Approval Handlers (Phase 104)
import {
  handleGetPatchApproval,
  handleListPatchApprovals,
  handleApprovePatch,
  handleRejectPatch,
  handleApplyPatch,
} from './patch-approval-handlers.js';

// Patch Rollback Handlers (Phase 105)
import {
  handlePlanPatchRollback,
  handleExecutePatchRollback,
  handleGetPatchRollback,
  handleListPatchRollbacks,
  handleResumePatchRollbackRecovery,
} from './patch-rollback-handlers.js';

// Retest Handlers (Phase 106)
import {
  handleCreateChangeSnapshot,
  handlePlanRetest,
  handleGetRetestPlan,
  handleListRetestPlans,
  handleExplainTestSelection,
} from './retest-handlers.js';

// PostFix Handlers (Phase 107)
import {
  handleExecutePostFixSync,
  handleRetryPostFixSync,
  handleGetPostFixSyncStatus,
  handleListPostFixSyncHistory,
} from './post-fix-handlers.js';

// Audit Handlers (Phase 108)
import {
  handleGetRepairTimeline,
  handleGetRepairSession,
  handleListRepairSessions,
  handleExportRepairTimeline,
  handleRecordRepairAuditEvent,
} from './audit-handlers.js';

// QA Report Handlers (Phase 109)
import {
  handleGenerateQaReport,
  handleGetQaReport,
  handleListQaReports,
  handleFinalizeQaReport,
  handleExportQaReport,
  handleEvaluateReleasePolicy,
  handleCheckQaReportStaleness,
} from './qa-report-handlers.js';

export type SafeIpcHandlerWrapper = <T, A extends unknown[] = unknown[]>(
  channelOrFn: string | ((event: IpcMainInvokeEvent, ...args: A) => T | Promise<T>),
  maybeFn?: (event: IpcMainInvokeEvent, ...args: A) => T | Promise<T>,
) => (event: IpcMainInvokeEvent, ...args: A) => Promise<DesktopResult<T>>;

export const FAILURE_AND_DEFECT_CHANNELS_MAP: ReadonlyArray<
  readonly [string, (event: IpcMainInvokeEvent, payload: unknown) => Promise<any>]
> = [
  // --- Failure Intelligence (V6 Phase 74-87) ---
  [DESKTOP_CHANNELS.FAILURES_CREATE_CASE, handleCreateFailureCase],
  [DESKTOP_CHANNELS.FAILURES_ENSURE_CASE, handleEnsureFailureCase],
  [DESKTOP_CHANNELS.FAILURES_GET_CASE, handleGetFailureCase],
  [DESKTOP_CHANNELS.FAILURES_LIST_CASES, handleListFailureCases],
  [DESKTOP_CHANNELS.FAILURES_START_ANALYSIS, handleStartFailureAnalysis],
  [DESKTOP_CHANNELS.FAILURES_COMPLETE_ANALYSIS, handleCompleteFailureAnalysis],
  [DESKTOP_CHANNELS.FAILURES_FAIL_ANALYSIS, handleFailFailureAnalysis],
  [DESKTOP_CHANNELS.FAILURES_CANCEL_ANALYSIS, handleCancelFailureAnalysis],
  [DESKTOP_CHANNELS.FAILURES_MARK_STALE, handleMarkFailureCaseStale],
  [DESKTOP_CHANNELS.FAILURES_LIST_RUNS, handleListFailureAnalysisRuns],
  [DESKTOP_CHANNELS.FAILURES_LIST_EVIDENCE_REFERENCES, handleListFailureEvidenceReferences],
  [DESKTOP_CHANNELS.FAILURES_INGEST_EVIDENCE, handleIngestFailureEvidence],
  [DESKTOP_CHANNELS.FAILURES_GET_EVIDENCE_PACKAGE, handleGetFailureEvidencePackage],
  [DESKTOP_CHANNELS.FAILURES_VERIFY_EVIDENCE_INTEGRITY, handleVerifyEvidenceIntegrity],
  [DESKTOP_CHANNELS.FAILURES_GET_EVIDENCE_ARTIFACT_CONTENT, handleGetEvidenceArtifactContent],
  [DESKTOP_CHANNELS.FAILURES_EXECUTE_REPRODUCTION, handleExecuteReproduction],
  [DESKTOP_CHANNELS.FAILURES_GET_REPRODUCTION_ATTEMPTS, handleGetReproductionAttempts],
  [DESKTOP_CHANNELS.FAILURES_GET_REPRODUCIBILITY_SUMMARY, handleGetReproducibilitySummary],
  [DESKTOP_CHANNELS.FAILURES_CANCEL_REPRODUCTION, handleCancelReproduction],
  [DESKTOP_CHANNELS.FAILURES_CLASSIFY, handleClassifyFailure],
  [DESKTOP_CHANNELS.FAILURES_GET_CLASSIFICATION, handleGetFailureClassification],
  [DESKTOP_CHANNELS.FAILURES_RECLASSIFY, handleReclassifyFailure],
  [DESKTOP_CHANNELS.FAILURES_LIST_CLASSIFICATION_HISTORY, handleListFailureClassificationHistory],
  [DESKTOP_CHANNELS.FAILURES_EVALUATE_DECISION_INTEGRITY, handleEvaluateDecisionIntegrity],
  [DESKTOP_CHANNELS.FAILURES_GET_DECISION_INTEGRITY, handleGetDecisionIntegrity],
  [DESKTOP_CHANNELS.FAILURES_RECOMPUTE_DECISION_INTEGRITY, handleRecomputeDecisionIntegrity],
  [DESKTOP_CHANNELS.FAILURES_LIST_DECISION_INTEGRITY_HISTORY, handleListDecisionIntegrityHistory],
  [DESKTOP_CHANNELS.FAILURES_ANALYZE_FLAKINESS, handleAnalyzeFlakiness],
  [DESKTOP_CHANNELS.FAILURES_GET_FLAKINESS_ANALYSIS, handleGetFlakinessAnalysis],
  [DESKTOP_CHANNELS.FAILURES_REANALYZE_FLAKINESS, handleReanalyzeFlakiness],
  [DESKTOP_CHANNELS.FAILURES_LIST_FLAKINESS_HISTORY, handleListFlakinessHistory],
  [DESKTOP_CHANNELS.FAILURES_SEPARATE_FAILURE_DOMAIN, handleSeparateFailureDomain],
  [DESKTOP_CHANNELS.FAILURES_GET_DOMAIN_SEPARATION, handleGetDomainSeparation],
  [DESKTOP_CHANNELS.FAILURES_REEVALUATE_DOMAIN_SEPARATION, handleReevaluateDomainSeparation],
  [DESKTOP_CHANNELS.FAILURES_LIST_DOMAIN_SEPARATION_HISTORY, handleListDomainSeparationHistory],
  [DESKTOP_CHANNELS.FAILURES_LOCALIZE_TECHNICAL_CAUSE, handleLocalizeTechnicalCause],
  [DESKTOP_CHANNELS.FAILURES_GET_TECHNICAL_LOCALIZATION, handleGetTechnicalLocalization],
  [DESKTOP_CHANNELS.FAILURES_RELOCALIZE_TECHNICAL_CAUSE, handleRelocalizeTechnicalCause],
  [DESKTOP_CHANNELS.FAILURES_LIST_LOCALIZATION_HISTORY, handleListLocalizationHistory],
  [DESKTOP_CHANNELS.FAILURES_ASSESS_WITH_AI, handleAssessFailureWithAi],
  [DESKTOP_CHANNELS.FAILURES_GET_AI_ASSESSMENT, handleGetFailureAiAssessment],
  [DESKTOP_CHANNELS.FAILURES_REASSESS_WITH_AI, handleReassessFailureWithAi],
  [DESKTOP_CHANNELS.FAILURES_LIST_AI_ASSESSMENT_HISTORY, handleListFailureAiAssessmentHistory],
  [DESKTOP_CHANNELS.FAILURES_ANALYZE_ROOT_CAUSE, handleAnalyzeRootCause],
  [DESKTOP_CHANNELS.FAILURES_GET_ROOT_CAUSE_ANALYSIS, handleGetRootCauseAnalysis],
  [DESKTOP_CHANNELS.FAILURES_REANALYZE_ROOT_CAUSE, handleReanalyzeRootCause],
  [DESKTOP_CHANNELS.FAILURES_LIST_ROOT_CAUSE_HISTORY, handleListRootCauseHistory],
  [DESKTOP_CHANNELS.FAILURES_ASSESS_IMPACT, handleAssessImpact],
  [DESKTOP_CHANNELS.FAILURES_GET_IMPACT_ASSESSMENT, handleGetImpactAssessment],
  [DESKTOP_CHANNELS.FAILURES_REASSESS_IMPACT, handleReassessImpact],
  [DESKTOP_CHANNELS.FAILURES_LIST_IMPACT_HISTORY, handleListImpactHistory],
  [DESKTOP_CHANNELS.FAILURES_COMPARE_DUPLICATE, handleCompareDuplicates],
  [DESKTOP_CHANNELS.FAILURES_CLUSTER_DEFECTS, handleClusterDefects],
  [DESKTOP_CHANNELS.FAILURES_GET_CLUSTER, handleGetCluster],
  [DESKTOP_CHANNELS.FAILURES_LIST_CLUSTERS, handleListClusters],
  [DESKTOP_CHANNELS.FAILURES_GET_FAILURE_MEMBERSHIP, handleGetFailureMembership],
  [DESKTOP_CHANNELS.FAILURES_MERGE_CLUSTERS, handleMergeClusters],
  [DESKTOP_CHANNELS.FAILURES_SPLIT_CLUSTER, handleSplitCluster],
  [DESKTOP_CHANNELS.FAILURES_OVERRIDE_MEMBERSHIP, handleOverrideMembership],
  [DESKTOP_CHANNELS.FAILURES_LIST_CLUSTER_HISTORY, handleListClusterHistory],
  [DESKTOP_CHANNELS.FAILURES_ASSESS_CONFIDENCE, handleAssessConfidence],
  [DESKTOP_CHANNELS.FAILURES_GET_CONFIDENCE, handleGetConfidence],
  [DESKTOP_CHANNELS.FAILURES_REASSESS_CONFIDENCE, handleReassessConfidence],
  [DESKTOP_CHANNELS.FAILURES_LIST_CONFIDENCE_HISTORY, handleListConfidenceHistory],
  [DESKTOP_CHANNELS.FAILURES_LIST_EVIDENCE_ATTRIBUTIONS, handleListEvidenceAttributions],
  [DESKTOP_CHANNELS.FAILURES_CREATE_BUG_REPORT, handleCreateBugReport],
  [DESKTOP_CHANNELS.FAILURES_GET_BUG_REPORT, handleGetBugReport],
  [DESKTOP_CHANNELS.FAILURES_LIST_BUG_REPORTS, handleListBugReports],
  [DESKTOP_CHANNELS.FAILURES_REGENERATE_BUG_REPORT, handleRegenerateBugReport],
  [DESKTOP_CHANNELS.FAILURES_LIST_BUG_REPORT_HISTORY, handleListBugReportHistory],

  // --- Jira Integration Foundation (V7 Phase 89-94) ---
  [DESKTOP_CHANNELS.JIRA_CREATE_CONNECTION, handleCreateJiraConnection],
  [DESKTOP_CHANNELS.JIRA_UPDATE_CONNECTION, handleUpdateJiraConnection],
  [DESKTOP_CHANNELS.JIRA_GET_CONNECTION, handleGetJiraConnection],
  [DESKTOP_CHANNELS.JIRA_DELETE_CONNECTION, handleDeleteJiraConnection],
  [DESKTOP_CHANNELS.JIRA_VALIDATE_CONNECTION, handleValidateJiraConnection],
  [DESKTOP_CHANNELS.JIRA_LIST_AUDIT_LOG, handleListJiraAuditLog],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_SITES, handleDiscoverJiraSites],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_PROJECTS, handleDiscoverJiraProjects],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_ISSUE_TYPES, handleDiscoverJiraIssueTypes],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_PRIORITIES, handleDiscoverJiraPriorities],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_FIELDS, handleDiscoverJiraFields],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_COMPONENTS, handleDiscoverJiraComponents],
  [DESKTOP_CHANNELS.JIRA_DISCOVER_ASSIGNEES, handleDiscoverJiraAssignees],
  [DESKTOP_CHANNELS.JIRA_GET_PROJECT_CONFIG, handleGetJiraProjectConfig],
  [DESKTOP_CHANNELS.JIRA_SAVE_PROJECT_CONFIG, handleSaveJiraProjectConfig],
  [DESKTOP_CHANNELS.JIRA_REFRESH_PROJECT_CONFIG, handleRefreshJiraProjectConfig],
  [DESKTOP_CHANNELS.JIRA_TEST_CONNECTION_HEALTH, handleTestJiraConnectionHealth],
  [DESKTOP_CHANNELS.JIRA_CREATE_ISSUE, handleCreateJiraIssue],
  [DESKTOP_CHANNELS.JIRA_GET_ISSUE, handleGetJiraIssue],
  [DESKTOP_CHANNELS.JIRA_LIST_ATTACHABLE_EVIDENCE, handleListAttachableEvidence],
  [DESKTOP_CHANNELS.JIRA_ATTACH_EVIDENCE, handleAttachEvidence],
  [DESKTOP_CHANNELS.JIRA_GET_ATTACHMENT_STATUS, handleGetAttachmentStatus],
  [DESKTOP_CHANNELS.JIRA_EVALUATE_DUPLICATE, handleEvaluateDuplicate],
  [DESKTOP_CHANNELS.JIRA_LINK_EXISTING_ISSUE, handleLinkExistingIssue],
  [DESKTOP_CHANNELS.JIRA_GET_ISSUE_LINK, handleGetIssueLink],
  [DESKTOP_CHANNELS.JIRA_REGISTER_PROJECT_ENGINEER, handleRegisterProjectEngineer],
  [DESKTOP_CHANNELS.JIRA_LIST_ELIGIBLE_ENGINEERS, handleListEligibleEngineers],
  [DESKTOP_CHANNELS.JIRA_GET_DEFECT_OWNERSHIP, handleGetDefectOwnership],
  [DESKTOP_CHANNELS.JIRA_ASSIGN_ENGINEER, handleAssignEngineer],
  [DESKTOP_CHANNELS.JIRA_UNASSIGN_ENGINEER, handleUnassignEngineer],
  [DESKTOP_CHANNELS.JIRA_SYNC_OWNERSHIP_FROM_JIRA, handleSyncOwnershipFromJira],
  [DESKTOP_CHANNELS.JIRA_RETRY_JIRA_SYNC, handleRetryJiraSync],

  // --- Email Notifications (Phase 95) ---
  [DESKTOP_CHANNELS.EMAIL_GET_CONFIG, handleGetEmailConfig],
  [DESKTOP_CHANNELS.EMAIL_SAVE_CONFIG, handleSaveEmailConfig],
  [DESKTOP_CHANNELS.EMAIL_TEST_CONNECTION, handleTestEmailConnection],
  [DESKTOP_CHANNELS.EMAIL_LIST_NOTIFICATIONS, handleListEmailNotifications],
  [DESKTOP_CHANNELS.EMAIL_GET_NOTIFICATION, handleGetEmailNotification],
  [DESKTOP_CHANNELS.EMAIL_RETRY_NOTIFICATION, handleRetryEmailNotification],
  [DESKTOP_CHANNELS.EMAIL_SEND_WORKFLOW_NOTIFICATION, handleSendWorkflowNotification],

  // --- Workflow Synchronization (Phase 96) ---
  [DESKTOP_CHANNELS.WORKFLOW_GET_STATE, handleGetWorkflowState],
  [DESKTOP_CHANNELS.WORKFLOW_UPDATE_INTERNAL_STATUS, handleUpdateInternalStatus],
  [DESKTOP_CHANNELS.WORKFLOW_GET_STATUS_MAPPINGS, handleGetWorkflowStatusMappings],
  [DESKTOP_CHANNELS.WORKFLOW_SAVE_STATUS_MAPPING, handleSaveWorkflowStatusMapping],
  [DESKTOP_CHANNELS.WORKFLOW_DELETE_STATUS_MAPPING, handleDeleteWorkflowStatusMapping],
  [DESKTOP_CHANNELS.WORKFLOW_SYNC_NOW, handleSyncWorkflowNow],
  [DESKTOP_CHANNELS.WORKFLOW_RESOLVE_CONFLICT, handleResolveWorkflowConflict],
  [DESKTOP_CHANNELS.WORKFLOW_LIST_SYNC_EVENTS, handleListWorkflowSyncEvents],

  // --- Reverification (Phase 97) ---
  [DESKTOP_CHANNELS.REVERIFICATION_GET_STATE, handleGetReverificationState],
  [DESKTOP_CHANNELS.REVERIFICATION_EVALUATE_ELIGIBILITY, handleEvaluateReverificationEligibility],
  [DESKTOP_CHANNELS.REVERIFICATION_CREATE_REQUEST, handleCreateReverificationRequest],
  [DESKTOP_CHANNELS.REVERIFICATION_GENERATE_PLAN, handleGenerateReverificationPlan],
  [DESKTOP_CHANNELS.REVERIFICATION_CANCEL, handleCancelReverification],
  [DESKTOP_CHANNELS.REVERIFICATION_LIST_AUDIT_EVENTS, handleListReverificationAuditEvents],

  // --- Verification (Phase 98) ---
  [DESKTOP_CHANNELS.VERIFICATION_EXECUTE, handleExecuteVerification],
  [DESKTOP_CHANNELS.VERIFICATION_GET_ATTEMPTS, handleGetVerificationAttempts],
  [DESKTOP_CHANNELS.VERIFICATION_GET_COMPARISON, handleGetVerificationComparison],
  [DESKTOP_CHANNELS.VERIFICATION_CANCEL, handleCancelVerification],

  // --- QuickFix (Phase 99) ---
  [DESKTOP_CHANNELS.QUICK_FIX_EVALUATE_ELIGIBILITY, handleEvaluateQuickFixEligibility],
  [DESKTOP_CHANNELS.QUICK_FIX_GET_ASSESSMENT, handleGetQuickFixAssessment],
  [DESKTOP_CHANNELS.QUICK_FIX_LIST_ASSESSMENTS, handleListQuickFixAssessments],

  // --- Defect Localization (Phase 100) ---
  [DESKTOP_CHANNELS.DEFECT_LOCALIZATION_LOCALIZE, handleLocalizeDefect],
  [DESKTOP_CHANNELS.DEFECT_LOCALIZATION_GET, handleGetDefectLocalization],
  [DESKTOP_CHANNELS.DEFECT_LOCALIZATION_LIST, handleListDefectLocalizations],
  [DESKTOP_CHANNELS.DEFECT_LOCALIZATION_INSPECT_SOURCE, handleInspectCandidateSource],

  // --- Patch Proposals (Phase 101) ---
  [DESKTOP_CHANNELS.PATCH_PROPOSAL_GENERATE, handleGeneratePatchProposal],
  [DESKTOP_CHANNELS.PATCH_PROPOSAL_GET, handleGetPatchProposal],
  [DESKTOP_CHANNELS.PATCH_PROPOSAL_LIST, handleListPatchProposals],
  [DESKTOP_CHANNELS.PATCH_PROPOSAL_WITHDRAW, handleWithdrawPatchProposal],

  // --- Patch Sandboxes (Phase 102) ---
  [DESKTOP_CHANNELS.PATCH_SANDBOX_CREATE, handleCreatePatchSandbox],
  [DESKTOP_CHANNELS.PATCH_SANDBOX_APPLY, handleApplyPatchToSandbox],
  [DESKTOP_CHANNELS.PATCH_SANDBOX_GET, handleGetPatchSandbox],
  [DESKTOP_CHANNELS.PATCH_SANDBOX_LIST, handleListPatchSandboxes],
  [DESKTOP_CHANNELS.PATCH_SANDBOX_DESTROY, handleDestroyPatchSandbox],

  // --- Patch Validation (Phase 103) ---
  [DESKTOP_CHANNELS.PATCH_VALIDATION_EXECUTE, handleExecutePatchValidation],
  [DESKTOP_CHANNELS.PATCH_VALIDATION_GET, handleGetPatchValidation],
  [DESKTOP_CHANNELS.PATCH_VALIDATION_LIST, handleListPatchValidations],
  [DESKTOP_CHANNELS.PATCH_VALIDATION_CANCEL, handleCancelPatchValidation],

  // --- Patch Approval (Phase 104) ---
  [DESKTOP_CHANNELS.PATCH_APPROVAL_GET, handleGetPatchApproval],
  [DESKTOP_CHANNELS.PATCH_APPROVAL_LIST, handleListPatchApprovals],
  [DESKTOP_CHANNELS.PATCH_APPROVAL_APPROVE, handleApprovePatch],
  [DESKTOP_CHANNELS.PATCH_APPROVAL_REJECT, handleRejectPatch],
  [DESKTOP_CHANNELS.PATCH_APPROVAL_APPLY, handleApplyPatch],

  // --- Patch Rollback (Phase 105) ---
  [DESKTOP_CHANNELS.PATCH_ROLLBACK_PLAN, handlePlanPatchRollback],
  [DESKTOP_CHANNELS.PATCH_ROLLBACK_EXECUTE, handleExecutePatchRollback],
  [DESKTOP_CHANNELS.PATCH_ROLLBACK_GET, handleGetPatchRollback],
  [DESKTOP_CHANNELS.PATCH_ROLLBACK_LIST, handleListPatchRollbacks],
  [DESKTOP_CHANNELS.PATCH_ROLLBACK_RESUME_RECOVERY, handleResumePatchRollbackRecovery],

  // --- Retest Planning & Execution (Phase 106) ---
  [DESKTOP_CHANNELS.RETEST_CREATE_SNAPSHOT, handleCreateChangeSnapshot],
  [DESKTOP_CHANNELS.RETEST_PLAN, handlePlanRetest],
  [DESKTOP_CHANNELS.RETEST_GET_PLAN, handleGetRetestPlan],
  [DESKTOP_CHANNELS.RETEST_LIST_PLANS, handleListRetestPlans],
  [DESKTOP_CHANNELS.RETEST_EXPLAIN_TEST, handleExplainTestSelection],

  // --- PostFix External Sync (Phase 107) ---
  [DESKTOP_CHANNELS.POST_FIX_SYNC_EXECUTE, handleExecutePostFixSync],
  [DESKTOP_CHANNELS.POST_FIX_SYNC_RETRY, handleRetryPostFixSync],
  [DESKTOP_CHANNELS.POST_FIX_SYNC_GET_STATUS, handleGetPostFixSyncStatus],
  [DESKTOP_CHANNELS.POST_FIX_SYNC_LIST_HISTORY, handleListPostFixSyncHistory],

  // --- Audit & History (Phase 108) ---
  [DESKTOP_CHANNELS.AUDIT_GET_TIMELINE, handleGetRepairTimeline],
  [DESKTOP_CHANNELS.AUDIT_GET_SESSION, handleGetRepairSession],
  [DESKTOP_CHANNELS.AUDIT_LIST_SESSIONS, handleListRepairSessions],
  [DESKTOP_CHANNELS.AUDIT_EXPORT_TIMELINE, handleExportRepairTimeline],
  [DESKTOP_CHANNELS.AUDIT_RECORD_EVENT, handleRecordRepairAuditEvent],

  // --- QA Release Report (Phase 109) ---
  [DESKTOP_CHANNELS.QA_REPORT_GENERATE, handleGenerateQaReport],
  [DESKTOP_CHANNELS.QA_REPORT_GET, handleGetQaReport],
  [DESKTOP_CHANNELS.QA_REPORT_LIST, handleListQaReports],
  [DESKTOP_CHANNELS.QA_REPORT_FINALIZE, handleFinalizeQaReport],
  [DESKTOP_CHANNELS.QA_REPORT_EXPORT, handleExportQaReport],
  [DESKTOP_CHANNELS.QA_REPORT_EVALUATE_POLICY, handleEvaluateReleasePolicy],
  [DESKTOP_CHANNELS.QA_REPORT_CHECK_STALENESS, handleCheckQaReportStaleness],
];

export const FAILURE_AND_DEFECT_ERROR_CODES: readonly DesktopErrorCode[] = [
  'FAILURE_CASE_NOT_FOUND',
  'EXECUTION_INELIGIBLE',
  'FAILURE_CASE_ALREADY_EXISTS',
  'INVALID_LIFECYCLE_TRANSITION',
  'ANALYSIS_ALREADY_RUNNING',
  'CROSS_PROJECT_MISMATCH',
  'FAILURE_ANALYSIS_RUN_NOT_FOUND',
  'FAILURE_EVIDENCE_NOT_FOUND',
  'EVIDENCE_INTEGRITY_FAILED',
  'EVIDENCE_ARTIFACT_MISSING',
  'EVIDENCE_CORRUPT',
  'EVIDENCE_PATH_TRAVERSAL_DETECTED',
  'EVIDENCE_INGESTION_FAILED',
  'REPRODUCTION_BLOCKED',
  'HISTORICAL_TEST_VERSION_UNAVAILABLE',
  'REPRODUCTION_ENVIRONMENT_INCOMPATIBLE',
  'REPRODUCTION_ATTEMPT_LIMIT_EXCEEDED',
  'REPRODUCTION_ALREADY_IN_PROGRESS',
  'REPRODUCTION_NOT_FOUND',
  'CLASSIFICATION_NOT_FOUND',
  'CLASSIFICATION_BLOCKED',
  'CLASSIFICATION_CONFLICT',
  'CLASSIFICATION_EVIDENCE_INSUFFICIENT',
  'CLASSIFICATION_ALREADY_EXISTS',
  'CLASSIFICATION_CONCURRENT_MUTATION',
  'DECISION_INTEGRITY_NOT_FOUND',
  'DECISION_INTEGRITY_STALE',
  'DECISION_INTEGRITY_INVALIDATED',
  'DECISION_INTEGRITY_CONFLICTED',
  'DECISION_INTEGRITY_INSUFFICIENT',
  'DECISION_INTEGRITY_BLOCKED',
  'DECISION_INTEGRITY_CONCURRENT_MUTATION',
  'FLAKINESS_ANALYSIS_NOT_FOUND',
  'FLAKINESS_ANALYSIS_STALE',
  'FLAKINESS_ANALYSIS_INSUFFICIENT_EVIDENCE',
  'FLAKINESS_ANALYSIS_BLOCKED',
  'FLAKINESS_ANALYSIS_CONCURRENT_MUTATION',
  'FLAKINESS_ANALYSIS_CROSS_PROJECT',
  'FAILURE_DOMAIN_NOT_FOUND',
  'FAILURE_DOMAIN_STALE',
  'FAILURE_DOMAIN_INSUFFICIENT_EVIDENCE',
  'FAILURE_DOMAIN_BLOCKED',
  'FAILURE_DOMAIN_CONCURRENT_MUTATION',
  'FAILURE_DOMAIN_CROSS_PROJECT',
  'LOCALIZATION_NOT_FOUND',
  'LOCALIZATION_STALE',
  'LOCALIZATION_INSUFFICIENT_EVIDENCE',
  'LOCALIZATION_BLOCKED',
  'LOCALIZATION_CROSS_PROJECT',
  'LOCALIZATION_CONCURRENT_MUTATION',
  'AI_ASSESSMENT_NOT_FOUND',
  'AI_ASSESSMENT_STALE',
  'AI_ASSESSMENT_UNAVAILABLE',
  'AI_ASSESSMENT_INSUFFICIENT_EVIDENCE',
  'AI_ASSESSMENT_BLOCKED',
  'AI_ASSESSMENT_CROSS_PROJECT',
  'AI_ASSESSMENT_CONCURRENT_MUTATION',
  'ROOT_CAUSE_NOT_FOUND',
  'ROOT_CAUSE_STALE',
  'ROOT_CAUSE_UNAVAILABLE',
  'ROOT_CAUSE_INSUFFICIENT_EVIDENCE',
  'ROOT_CAUSE_BLOCKED',
  'ROOT_CAUSE_CROSS_PROJECT',
  'ROOT_CAUSE_CONCURRENT_MUTATION',
  'IMPACT_ASSESSMENT_NOT_FOUND',
  'IMPACT_ASSESSMENT_STALE',
  'IMPACT_ASSESSMENT_UNAVAILABLE',
  'IMPACT_ASSESSMENT_INSUFFICIENT_EVIDENCE',
  'IMPACT_ASSESSMENT_BLOCKED',
  'IMPACT_ASSESSMENT_CROSS_PROJECT',
  'IMPACT_ASSESSMENT_CONCURRENT_MUTATION',
  'DEFECT_CLUSTER_NOT_FOUND',
  'DEFECT_CLUSTER_CROSS_PROJECT',
  'DEFECT_CLUSTER_INVALID_OPERATION',
  'DEFECT_CLUSTER_CONCURRENT_MUTATION',
  'DEFECT_CLUSTER_INSUFFICIENT_EVIDENCE',
  'DEFECT_CLUSTER_ALREADY_MEMBER',
  'DEFECT_CLUSTER_EMPTY_SPLIT',
  'CONFIDENCE_ASSESSMENT_NOT_FOUND',
  'CONFIDENCE_ASSESSMENT_STALE',
  'CONFIDENCE_ASSESSMENT_CROSS_PROJECT',
  'CONFIDENCE_ASSESSMENT_INVALID_OPERATION',
  'CONFIDENCE_ASSESSMENT_INSUFFICIENT_EVIDENCE',
  'CONFIDENCE_ASSESSMENT_CONCURRENT_MUTATION',
  'CONFIDENCE_INTEGRITY_VIOLATION',
  'BUG_REPORT_NOT_FOUND',
  'BUG_REPORT_STALE',
  'BUG_REPORT_CROSS_PROJECT',
  'BUG_REPORT_INVALID_OPERATION',
  'BUG_REPORT_INSUFFICIENT_EVIDENCE',
  'BUG_REPORT_CONCURRENT_MUTATION',
  'BUG_REPORT_INTEGRITY_VIOLATION',
  'JIRA_AUTHENTICATION_FAILED',
  'JIRA_PERMISSION_DENIED',
  'JIRA_CONNECTION_FAILED',
  'JIRA_REQUEST_TIMEOUT',
  'JIRA_RATE_LIMITED',
  'JIRA_INVALID_RESPONSE',
  'JIRA_CONFIGURATION_INVALID',
  'JIRA_CONNECTION_NOT_FOUND',
  'JIRA_SECURITY_VIOLATION',
  'JIRA_CONCURRENT_MUTATION',
  'JIRA_CROSS_PROJECT',
  'JIRA_PROJECT_NOT_FOUND',
  'JIRA_PROJECT_ACCESS_DENIED',
  'JIRA_ISSUE_TYPE_NOT_FOUND',
  'JIRA_PRIORITY_NOT_FOUND',
  'JIRA_CONFIG_NOT_FOUND',
  'JIRA_STALE_CONFIG',
  'JIRA_WRONG_PROJECT_METADATA',
  'JIRA_CONNECTION_EXPIRED',
  'JIRA_CONNECTION_REVOKED',
  'JIRA_SITE_UNREACHABLE',
  'JIRA_ISSUE_INELIGIBLE',
  'JIRA_ISSUE_CREATION_FAILED',
  'JIRA_ISSUE_ALREADY_EXISTS',
  'JIRA_BUG_REPORT_NOT_FOUND',
  'JIRA_ATTACHMENT_INELIGIBLE',
  'JIRA_EVIDENCE_NOT_FOUND',
  'JIRA_EVIDENCE_INTEGRITY_FAILED',
  'JIRA_EVIDENCE_TOO_LARGE',
  'JIRA_EVIDENCE_UNSUPPORTED_TYPE',
  'JIRA_ATTACHMENT_FAILED',
  'JIRA_DUPLICATE_FOUND',
  'JIRA_LINK_NOT_FOUND',
  'JIRA_LINK_INVALID',
  'JIRA_DEDUPLICATION_CONFLICT',
  'JIRA_DEFECT_CLUSTER_NOT_FOUND',
  'JIRA_ISSUE_NOT_FOUND',
  'JIRA_ENGINEER_INELIGIBLE',
  'JIRA_ENGINEER_NOT_FOUND',
  'JIRA_STALE_OWNERSHIP_VERSION',
  'JIRA_OWNERSHIP_NOT_FOUND',
  'JIRA_OWNERSHIP_CONFLICT',
  'EMAIL_CONFIGURATION_MISSING',
  'EMAIL_PROVIDER_UNAVAILABLE',
  'EMAIL_RECIPIENT_INVALID',
  'EMAIL_DELIVERY_FAILED',
  'EMAIL_ALREADY_SENT',
  'EMAIL_NOT_FOUND',
  'EMAIL_RETRY_LIMIT_EXCEEDED',
  'EMAIL_CROSS_PROJECT_FORBIDDEN',
  'WORKFLOW_STATE_NOT_FOUND',
  'WORKFLOW_INVALID_TRANSITION',
  'WORKFLOW_STATUS_UNMAPPED',
  'WORKFLOW_SYNC_CONFLICT',
  'WORKFLOW_EXTERNAL_ISSUE_NOT_FOUND',
  'WORKFLOW_SYNC_LOCKED',
  'WORKFLOW_CROSS_PROJECT_FORBIDDEN',
  'WORKFLOW_MAPPING_NOT_FOUND',
  'REVERIFICATION_NOT_FOUND',
  'REVERIFICATION_NOT_ELIGIBLE',
  'REVERIFICATION_BLOCKED',
  'REVERIFICATION_ALREADY_EXISTS',
  'REVERIFICATION_CROSS_PROJECT_FORBIDDEN',
  'REVERIFICATION_UNSAFE_ENVIRONMENT',
  'REVERIFICATION_HISTORICAL_TEST_UNAVAILABLE',
  'REVERIFICATION_IMMUTABLE',
  'REVERIFICATION_MANUAL_FIX_FORBIDDEN',
  'VERIFICATION_NOT_FOUND',
  'VERIFICATION_IN_PROGRESS',
  'VERIFICATION_ATTEMPT_LIMIT_EXCEEDED',
  'VERIFICATION_EXECUTION_FAILED',
  'VERIFICATION_BLOCKED',
  'VERIFICATION_ENVIRONMENT_INCOMPATIBLE',
  'VERIFICATION_CANCELLED',
  'QUICK_FIX_NOT_FOUND',
  'QUICK_FIX_STALE',
  'QUICK_FIX_BLOCKED',
  'QUICK_FIX_INSUFFICIENT_EVIDENCE',
  'QUICK_FIX_CROSS_PROJECT',
  'QUICK_FIX_CONCURRENT_MUTATION',
  'QUICK_FIX_SAFETY_POLICY_VIOLATION',
  'QUICK_FIX_GIT_DIRTY_WORKTREE',
  'QUICK_FIX_GIT_ERROR',
  'LOCALIZATION_REPOSITORY_NOT_FOUND',
  'LOCALIZATION_REVISION_UNAVAILABLE',
  'LOCALIZATION_PATH_TRAVERSAL_DETECTED',
  'LOCALIZATION_SYMLINK_ESCAPE_DETECTED',
  'LOCALIZATION_READ_ONLY_VIOLATION',
  'LOCALIZATION_FABRICATED_ENTITY_REJECTED',
  'PATCH_NOT_FOUND',
  'PATCH_INELIGIBLE',
  'PATCH_LOCALIZATION_REQUIRED',
  'PATCH_CROSS_PROJECT',
  'PATCH_CONCURRENT_MUTATION',
  'PATCH_REVISION_DRIFT',
  'PATCH_PATH_TRAVERSAL_DETECTED',
  'PATCH_UNAUTHORIZED_FILE',
  'PATCH_OVERSIZED',
  'PATCH_HIGH_RISK_BLOCKED',
  'PATCH_MALFORMED_DIFF',
  'PATCH_HALLUCINATED_ENTITY',
  'PATCH_DIRECT_MUTATION_FORBIDDEN',
  'PATCH_SANDBOX_NOT_FOUND',
  'PATCH_SANDBOX_ALREADY_EXISTS',
  'PATCH_SANDBOX_CREATION_FAILED',
  'PATCH_SANDBOX_REVISION_MISMATCH',
  'PATCH_SANDBOX_PATH_TRAVERSAL_DETECTED',
  'PATCH_SANDBOX_SYMLINK_ESCAPE_DETECTED',
  'PATCH_SANDBOX_UNAUTHORIZED_FILE',
  'PATCH_SANDBOX_SENSITIVE_FILE_BLOCKED',
  'PATCH_SANDBOX_GIT_METADATA_BLOCKED',
  'PATCH_SANDBOX_CONFLICT',
  'PATCH_SANDBOX_DIFF_MISMATCH',
  'PATCH_SANDBOX_OVERSIZED',
  'PATCH_SANDBOX_UNSUPPORTED_BINARY',
  'PATCH_SANDBOX_ALREADY_APPLIED',
  'PATCH_SANDBOX_CROSS_PROJECT',
  'PATCH_SANDBOX_CONCURRENT_MUTATION',
  'PATCH_SANDBOX_CLEANUP_FAILED',
  'PATCH_SANDBOX_IMMUTABILITY_VIOLATION',
  'PATCH_VALIDATION_NOT_FOUND',
  'PATCH_VALIDATION_IN_PROGRESS',
  'PATCH_VALIDATION_ALREADY_COMPLETED',
  'PATCH_VALIDATION_SANDBOX_UNAVAILABLE',
  'PATCH_VALIDATION_PROPOSAL_NOT_FOUND',
  'PATCH_VALIDATION_CROSS_PROJECT',
  'PATCH_VALIDATION_CONCURRENT_MUTATION',
  'PATCH_VALIDATION_TIMEOUT',
  'PATCH_VALIDATION_CANCELLED',
  'PATCH_VALIDATION_BEFORE_EXECUTION_FAILED',
  'PATCH_VALIDATION_PATCH_APPLICATION_FAILED',
  'PATCH_VALIDATION_REGRESSION_DETECTED',
  'PATCH_VALIDATION_QUALITY_GATE_FAILED',
  'PATCH_VALIDATION_UNEXPECTED_CHANGES',
  'PATCH_VALIDATION_SANDBOX_ESCAPE_ATTEMPT',
  'PATCH_APPROVAL_NOT_FOUND',
  'PATCH_APPROVAL_CROSS_PROJECT',
  'PATCH_APPROVAL_INVALID_STATE_TRANSITION',
  'PATCH_APPROVAL_VALIDATION_NOT_VALID',
  'PATCH_APPROVAL_STALE_VALIDATION',
  'PATCH_APPROVAL_HASH_MISMATCH',
  'PATCH_APPROVAL_REPOSITORY_DRIFT',
  'PATCH_APPROVAL_NOT_APPROVED',
  'PATCH_APPROVAL_ALREADY_APPLIED',
  'PATCH_APPROVAL_APPLY_FAILED',
  'PATCH_APPROVAL_SCOPE_VIOLATION',
  'PATCH_APPROVAL_CONCURRENT_MUTATION',
  'PATCH_ROLLBACK_NOT_FOUND',
  'PATCH_ROLLBACK_CROSS_PROJECT',
  'PATCH_ROLLBACK_INVALID_STATE',
  'PATCH_ROLLBACK_NOT_APPLIED',
  'PATCH_ROLLBACK_CONFLICT',
  'PATCH_ROLLBACK_DRIFT_DETECTED',
  'PATCH_ROLLBACK_RECOVERY_FAILED',
  'PATCH_ROLLBACK_INTEGRITY_FAILED',
  'PATCH_ROLLBACK_CONCURRENT_MUTATION',
  'PATCH_ROLLBACK_RECOVERY_REQUIRED',
  'RETEST_PLAN_NOT_FOUND',
  'RETEST_SNAPSHOT_NOT_FOUND',
  'RETEST_PROJECT_MISMATCH',
  'RETEST_VALIDATION_ERROR',
  'RETEST_PATCH_NOT_FOUND',
  'RETEST_REQUIREMENT_NOT_FOUND',
  'RETEST_CONCURRENT_ANALYSIS_ERROR',
  'RETEST_UNBOUNDED_SCOPE_ERROR',
  'POST_FIX_SYNC_NOT_FOUND',
  'POST_FIX_REVERIFICATION_NOT_FOUND',
  'POST_FIX_JIRA_LINK_NOT_FOUND',
  'POST_FIX_PROJECT_MISMATCH',
  'POST_FIX_VALIDATION_ERROR',
  'POST_FIX_UNAUTHORITATIVE_VERIFICATION',
  'POST_FIX_CONCURRENT_SYNC_ERROR',
  'POST_FIX_INVALID_TRANSITION',
  'POST_FIX_JIRA_RATE_LIMITED',
  'POST_FIX_JIRA_AUTH_FAILED',
  'POST_FIX_NOTIFICATION_FAILED',
  'AUDIT_SESSION_NOT_FOUND',
  'AUDIT_EVENT_NOT_FOUND',
  'AUDIT_IMMUTABILITY_VIOLATION',
  'AUDIT_PROJECT_MISMATCH',
  'AUDIT_VALIDATION_ERROR',
  'AUDIT_CONCURRENT_MUTATION',
  'AUDIT_EXPORT_FAILED',
  'QA_REPORT_NOT_FOUND',
  'QA_REPORT_ALREADY_FINAL',
  'QA_REPORT_IMMUTABILITY_VIOLATION',
  'QA_REPORT_PROJECT_MISMATCH',
  'QA_REPORT_VALIDATION_ERROR',
  'QA_REPORT_EXPORT_FAILED',
  'QA_REPORT_STALE_DATA',
  'QA_REPORT_CONCURRENT_MUTATION',
];

/**
 * Register all Failure Intelligence, Jira, and Defect Remediation IPC channels.
 */
export function registerFailureAndDefectIpc(
  ipcMain: IpcMain,
  createSafeIpcHandler: SafeIpcHandlerWrapper,
): void {
  for (const [channel, handler] of FAILURE_AND_DEFECT_CHANNELS_MAP) {
    ipcMain.handle(
      channel,
      createSafeIpcHandler(channel, (event: IpcMainInvokeEvent, payload: unknown) =>
        handler(event, payload),
      ),
    );
  }
}

/**
 * Unregister all Failure Intelligence, Jira, and Defect Remediation IPC channels.
 */
export function unregisterFailureAndDefectIpc(ipcMain: IpcMain): void {
  for (const [channel] of FAILURE_AND_DEFECT_CHANNELS_MAP) {
    ipcMain.removeHandler(channel);
  }
}
