/**
 * @file packages/core/src/ai/test-design/test-design-types.ts
 * Types and constants for Test Design Intelligence Foundation.
 */

export const TEST_DESIGN_PROMPT_ID = 'test.design.intelligence';
export const TEST_DESIGN_PROMPT_VERSION = 1;
export const TEST_DESIGN_ENGINE_VERSION = 'test-design-rules-v1';

export const TEST_DESIGN_LIMITS = {
  MAX_RECOMMENDED_LEVELS: 10,
  MAX_RECOMMENDED_DIMENSIONS: 30,
  MAX_RECOMMENDED_TECHNIQUES: 25,
  MAX_COVERAGE_OBJECTIVES: 50,
  MAX_RISK_AREAS: 20,
  MAX_IDENTIFIED_CONSTRAINTS: 50,
  MAX_DESIGN_QUESTIONS: 25,
  MAX_RATIONALE_ITEMS: 50,
  MAX_SOURCE_CONTEXT_ITEMS: 30,
  MAX_PAYLOAD_CHARS: 100_000,
} as const;

export const TEST_DESIGN_REASON_CODES = {
  EXPLICIT_NUMERIC_RANGE: 'EXPLICIT_NUMERIC_RANGE',
  EXPLICIT_ENUMERATION: 'EXPLICIT_ENUMERATION',
  ROLE_RESTRICTION_PRESENT: 'ROLE_RESTRICTION_PRESENT',
  MULTI_CONDITION_RULE: 'MULTI_CONDITION_RULE',
  STATE_MACHINE_PRESENT: 'STATE_MACHINE_PRESENT',
  SECURITY_CLASSIFICATION: 'SECURITY_CLASSIFICATION',
  PERFORMANCE_THRESHOLD_PRESENT: 'PERFORMANCE_THRESHOLD_PRESENT',
  DEPENDENT_REQUIREMENTS_PRESENT: 'DEPENDENT_REQUIREMENTS_PRESENT',
  VALIDATION_LANGUAGE_PRESENT: 'VALIDATION_LANGUAGE_PRESENT',
  NEGATIVE_MODALITY_PRESENT: 'NEGATIVE_MODALITY_PRESENT',
  INSUFFICIENT_TESTABILITY: 'INSUFFICIENT_TESTABILITY',
  HIGH_RISK_REQUIREMENT: 'HIGH_RISK_REQUIREMENT',
  REPOSITORY_EVIDENCE_PRESENT: 'REPOSITORY_EVIDENCE_PRESENT',
  EXTERNAL_INTEGRATION_PRESENT: 'EXTERNAL_INTEGRATION_PRESENT',
  AMBIGUOUS_SPECIFICATION: 'AMBIGUOUS_SPECIFICATION',
  DATA_INTEGRITY_SENSITIVE: 'DATA_INTEGRITY_SENSITIVE',
  PURE_COMPUTATION_LOGIC: 'PURE_COMPUTATION_LOGIC',
  WORKFLOW_PROCESS_FLOW: 'WORKFLOW_PROCESS_FLOW',
} as const;

export type TestDesignReasonCode =
  (typeof TEST_DESIGN_REASON_CODES)[keyof typeof TEST_DESIGN_REASON_CODES];
